/*import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const tags = [
    { tag: "SSS-ST-001", unidade: "GARAGEM", local: "SALA TI/CPD/CFTV" },
    { tag: "SSS-ST-002", unidade: "GARAGEM", local: "SALA TI/CPD/CFTV" },
    { tag: "SPT-HE-001", unidade: "SEDE PISO TÉRREO", local: "HALL ELEVADOR" },
    { tag: "SPT-CX-002", unidade: "SEDE PISO TÉRREO", local: "CX ELETRÔNICO" },
    { tag: "SPT-RE-003", unidade: "SEDE PISO TÉRREO", local: "RECEPÇÃO" },
    { tag: "SPT-ES-004", unidade: "SEDE PISO TÉRREO", local: "ESPERA" },
    { tag: "SPT-AT-005", unidade: "SEDE PISO TÉRREO", local: "ATENDIMENTO" },
    { tag: "SPT-AT-006", unidade: "SEDE PISO TÉRREO", local: "ATENDIMENTO" },
    { tag: "SPT-GA-007", unidade: "SEDE PISO TÉRREO", local: "GERENCIA ATENDIMENTO" },
    { tag: "SPT-GA-008", unidade: "SEDE PISO TÉRREO", local: "GERENCIA ATENDIMENTO" },
    { tag: "SPT-AG-009", unidade: "SEDE PISO TÉRREO", local: "AGÊNCIA" },
    { tag: "SPT-AG-010", unidade: "SEDE PISO TÉRREO", local: "AGÊNCIA" },
    { tag: "SPT-TE-011", unidade: "SEDE PISO TÉRREO", local: "TESOURARIA" },
    { tag: "SPT-LC-012", unidade: "SEDE PISO TÉRREO", local: "LOUNGE CAFE" },
    { tag: "SPT-AS-013", unidade: "SEDE PISO TÉRREO", local: "ATENDIMENTO SEGURO" },
    { tag: "SPT-AS-014", unidade: "SEDE PISO TÉRREO", local: "ATENDIMENTO SEGURO" },
    { tag: "SPT-CE-015", unidade: "SEDE PISO TÉRREO", local: "CORREDOR E ENTRADA" },
    { tag: "SPT-CE-016", unidade: "SEDE PISO TÉRREO", local: "CORREDOR E ENTRADA" },
    { tag: "SPT-AL-017", unidade: "SEDE PISO TÉRREO", local: "ANÁLISE TECNICA" },
    { tag: "SPT-CO-018", unidade: "SEDE PISO TÉRREO", local: "COPA" },
    { tag: "SPT-GU-019", unidade: "SEDE PISO TÉRREO", local: "GUARITA" },
    { tag: "SPT-NB-020", unidade: "SEDE PISO TÉRREO", local: "SALA DO NOBREAK" },
    { tag: "SPS-HE-001 ", unidade: "SEDE PISO SUPERIOR", local: "HALL ELEVADOR" },
    { tag: "SPS-HE-002", unidade: "SEDE PISO SUPERIOR", local: "HALL ELEVADOR" },
    { tag: "SPS-CE-003", unidade: "SEDE PISO SUPERIOR", local: "CORREDOR E ENTRADA" },
    { tag: "SPS-CE-004", unidade: "SEDE PISO SUPERIOR", local: "CORREDOR E ENTRADA" },
    { tag: "SPS-SR-005", unidade: "SEDE PISO SUPERIOR", local: "REUNIÃO" },
    { tag: "SPS-SR-006", unidade: "SEDE PISO SUPERIOR", local: "REUNIÃO" },
    { tag: "SPS-SC-007", unidade: "SEDE PISO SUPERIOR", local: "CONSELHO" },
    { tag: "SPS-SP-008", unidade: "SEDE PISO SUPERIOR", local: "PRESIDÊNCIA CONSELHO" },
    { tag: "SPS-RE-009", unidade: "SEDE PISO SUPERIOR", local: "RECEPÇÃO" },
    { tag: "SPS-LE-010", unidade: "SEDE PISO SUPERIOR", local: "LOUNGE ESPERA" },
    { tag: "SPS-SD-011", unidade: "SEDE PISO SUPERIOR", local: "DIRETORIA OPERACIONAL" },
    { tag: "SPS-SD-012", unidade: "SEDE PISO SUPERIOR", local: "ASSESSORIA PRESIDÊNCIA" },
    { tag: "SPS-SD-013", unidade: "SEDE PISO SUPERIOR", local: "DIRETOR PRESIDENTE" },
    { tag: "SPS-AU-014", unidade: "SEDE PISO SUPERIOR", local: "AUDITÓRIO" },
    { tag: "SPS-AU-015", unidade: "SEDE PISO SUPERIOR", local: "AUDITÓRIO" },
    { tag: "SPS-AU-016", unidade: "SEDE PISO SUPERIOR", local: "AUDITÓRIO" },
    { tag: "SPS-AU-017", unidade: "SEDE PISO SUPERIOR", local: "AUDITÓRIO" },
    { tag: "APT-SA-001", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-SA-002", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-SA-003", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-SA-004", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-SA-005", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-SA-006", unidade: "ANEXO PISO TÉRREO", local: "SALA ADMINISTRAÇÃO" },
    { tag: "APT-AL-007", unidade: "ANEXO PISO TÉRREO", local: "SALA ALMOXARIFADO" },
    { tag: "APT-SI-008", unidade: "ANEXO PISO TÉRREO", local: "SALA TECNO INFO" },
    { tag: "APT-SI-009", unidade: "ANEXO PISO TÉRREO", local: "SALA TECNO INFO" },
    { tag: "APT-SI-010", unidade: "ANEXO PISO TÉRREO", local: "SALA TECNO INFO" },
    { tag: "APS-RF-001", unidade: "ANEXO PISO SUPERIOR", local: "REFEITÓRIO" },
    { tag: "APS-RF-002", unidade: "ANEXO PISO SUPERIOR", local: "REFEITÓRIO" },
    { tag: "APS-RF-003", unidade: "ANEXO PISO SUPERIOR", local: "REFEITÓRIO" },
    { tag: "APS-RF-004", unidade: "ANEXO PISO SUPERIOR", local: "REFEITÓRIO" },
    { tag: "APS-RF-005", unidade: "ANEXO PISO SUPERIOR", local: "REFEITÓRIO / DESCOMPRESSÃO" },
    { tag: "CPT-GU-001", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "GUARITA" },
    { tag: "CPT-RE-002", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "RECEPÇÃO" },
    { tag: "CPT-RE-003", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "RECEPÇÃO" },
    { tag: "CPT-RE-004", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "RECEPÇÃO" },
    { tag: "CPT-AU-005", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "AUDITÓRIO" },
    { tag: "CPT-AU-006", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "AUDITÓRIO" },
    { tag: "CPT-ST-007", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "GERENCIA ATENDIMENTO PJ" },
    { tag: "CPT-SC-008", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "SALA DE COSTURA" },
    { tag: "CPT-CO-009", unidade: "CENTRO DE CONVIVENCIA PISO TÉRREO", local: "COPA/COZINHA" },
    { tag: "CPS-RE-001", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "RECEPÇÃO/SALA CONSELHO" },
    { tag: "CPS-SA-002", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA ADMINISTRAÇÃO" },
    { tag: "CPS-SP-003", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA PODCAST" },
    { tag: "CPS-ST-004", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA TREINAMENTO" },
    { tag: "CPS-ST-005", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA TREINAMENTO" },
    { tag: "CPS-ST-006", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA TREINAMENTO" },
    { tag: "CPS-ST-007", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA TREINAMENTO" },
    { tag: "CPS-SP-004", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA PESSOAL CALLCENTER" },
    { tag: "CPS-ST-005", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "SALA TI/CPD/CFTV" },
    { tag: "CPS-AD-006", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "ANFITEATRO E DANÇA" },
    { tag: "CPS-AD-007", unidade: "CENTRO DE CONVIVENCIA PISO SUPERIOR", local: "ANFITEATRO E DANÇA" },
    { tag: "AST-TI-001", unidade: "AG SATÉLITE ", local: "SALA TI/CPD/CFTV" },
    { tag: "AST-AT-002", unidade: "AG SATÉLITE", local: "ATENDIMENTO" },
    { tag: "AJA-AT-001", unidade: "AG JAMBEIRO", local: "ATENDIMENTO" },
    { tag: "AJA-AT-002", unidade: "AG JAMBEIRO", local: "ATENDIMENTO" },
    { tag: "AJA-AT-003", unidade: "AG JAMBEIRO", local: "ATENDIMENTO" },
    { tag: "AJA-CO-004", unidade: "AG JAMBEIRO", local: "COPA" },
    { tag: "AJA-TI-005", unidade: "AG JAMBEIRO", local: "SALA TI/CFTV/NOBREAK" },
    { tag: "APA-AT-001", unidade: "AG PARAIBUNA CEDRAP", local: "ATENDIMENTO" },
    { tag: "APA-AT-002", unidade: "AG PARAIBUNA CEDRAP", local: "ATENDIMENTO" },
    { tag: "APA-AT-003", unidade: "AG PARAIBUNA CEDRAP", local: "ATENDIMENTO" },
    { tag: "APA-AT-004", unidade: "AG PARAIBUNA CEDRAP", local: "ATENDIMENTO" },
    { tag: "APA-CX-005", unidade: "AG PARAIBUNA CEDRAP", local: "ATM" },
    { tag: "APA-TI-006", unidade: "AG PARAIBUNA CEDRAP", local: "SALA TI/CFTV/NOBREAK" },
    { tag: "ACP-AT-001", unidade: "PA CAÇAPAVA", local: "ATENDIMENTO" },
    { tag: "ACJ-AT-001", unidade: "PA CAMPOS DE JORDÃO", local: "ATENDIMENTO" },
    { tag: "ACG-AT-001", unidade: "PA CARAGUÁ", local: "ATENDIMENTO" },
    { tag: "ACR-AT-001", unidade: "PA CRUZEIRO ", local: "ATENDIMENTO" },
    { tag: "AEM-AT-001", unidade: "PA EUGENIO DE MELO", local: "ATENDIMENTO" },
    { tag: "AIB-AT-001", unidade: "PA ILHA BELA", local: "ATENDIMENTO" },
    { tag: "AJC-AT-001", unidade: "PA JACAREÍ", local: "ATENDIMENTO ESPERA" },
    { tag: "AJC-AT-002", unidade: "PA JACAREÍ", local: "ATENDIMENTO" },
    { tag: "AJM-AT-001", unidade: "PA ORIENTE", local: "ATENDIMENTO" },
    { tag: "APA-AT-007", unidade: "PA PARAIBUNA CENTRO", local: "ATENDIMENTO" },
    { tag: "ASB-AT-001", unidade: "PA SÃO SEBASTIÃO", local: "ATENDIMENTO" },
    { tag: "ASB-AT-002", unidade: "PA SÃO SEBASTIÃO", local: "ATENDIMENTO" },
    { tag: "AST-AT-003", unidade: "PA SATÉLITE", local: "ATENDIMENTO" },
    { tag: "AST-AT-004", unidade: "PA SATÉLITE", local: "ATENDIMENTO" },
    { tag: "ASF-AT-001", unidade: "PA SFX", local: "ATENDIMENTO" },
    { tag: "ASF-AT-002", unidade: "PA SFX", local: "ATENDIMENTO SEBRAE" },
    { tag: "ATB-AT-001", unidade: "PA TAUBATÉ", local: "ATENDIMENTO" },
    { tag: "AUB-AT-001", unidade: "PA UBATUBA", local: "ATENDIMENTO" },
  ];

  for (const item of tags) {
    await prisma.tag.upsert({
      where: { tag: item.tag },
      update: {
        unidade: item.unidade,
        local: item.local
      },
      create: item
    });
  }
}

main()
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());*/